plugins {
    id 'idea'
    id 'java'
    id 'com.azuredoom.hytale-tools' version '1.+'
    id 'com.gradleup.shadow' version "9.4.2"
}

javadoc {
    options.addStringOption('Xdoclint:-missing', '-quiet')
}

group = project.group

base {
  archivesName = project.mod_name.toString()
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

def lombokVersion = "1.18.40"
dependencies {
    compileOnly("org.jetbrains:annotations:26.1.0")
    compileOnly("org.jspecify:jspecify:1.0.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    implementation("curse.maven:creditor-1560961:8768657")

    compileOnly("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")
}

hytaleTools {
    javaVersion = project.java_version as Integer
    hytaleVersion = project.hytale_version.toString()
    manifestServerVersion = project.manifestServerVersion.toString()
    manifestGroup = project.manifest_group.toString()
    modId = project.mod_id.toString()
    modDescription = project.mod_description.toString()
    modUrl = project.mod_url.toString()
    mainClass = project.main_class.toString()
    modCredits = project.mod_author.toString()
    manifestDependencies = project.manifest_dependencies.toString()
    manifestOptionalDependencies = project.manifest_opt_dependencies.toString()
    curseforgeId = project.curseforgeID.toString()
    disabledByDefault = project.disabled_by_default.toString().toBoolean()
    includesPack = project.includes_pack.toString().toBoolean()
    injectServerJavadocsIntoSources = project.inject_server_javadocs_into_sources.toString().toBoolean()
    generateAssetsBinary = project.generateAssetsBinary.toString().toBoolean()
    patchline = project.patchline.toString()
}

repositories {
    mavenCentral()
    maven { url "https://www.cursemaven.com" }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.named('jar') {
    archiveBaseName.set(project.mod_name)
    archiveVersion.set(project.version)
    archiveClassifier.set('plain')
}

tasks.named('shadowJar') {
    archiveClassifier.set('')
    mergeServiceFiles()
}

// Ensure the shaded jar is produced during a normal build.
tasks.named('build') {
    dependsOn 'shadowJar'
}
